# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - wtgonlinehelp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_5fa4ac6633d64047826bb4a024f4c368 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_87d3440518074a4e974e9e058b623fda }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5fa4ac6633d64047826bb4a024f4c368 }}/YOUR_DOCKER_HUB_NAME/mm-help:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'wtgonlinehelp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_de0f4cc201034ffd92274b0136130ead }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5fa4ac6633d64047826bb4a024f4c368 }}/YOUR_DOCKER_HUB_NAME/mm-help:${{ github.sha }}'